### ISSUE TITLE
目前执行该文件报错

### ISSUE THREAD

**Issue by xialingsc** [hugojing/crawler#1]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)

**Comment by hugojing** [comment]
这是什么情况，Node 版本多少？

**Comment by xialingsc** [comment]
v4.2.2

2015-11-19 17:43 GMT+08:00 Hugo Jing notifications@github.com:

**Comment by hugojing** [comment]
目测程序没有问题。

**Comment by hugojing** [comment]
已修正这个 bug ，你可以再试一下。非常感谢。
